### ISSUE TITLE
Metrics collected in _collectHttpTiming cause overload in case URL has unique values

### ISSUE THREAD

**Issue by DavidFaizulaev** [Zooz/prometheus-api-metrics#25]
In '_collectHttpTiming' method, the metrics are collected directly using the request url.
So in case a URL has unique values, for example: 
For endpoint 'http://clients/{client_id}' and 2 requests
'http://clients/23342'
'http://clients/1111111'

Each will be written separately, instead of ignoring query params and just collecting timing for 'http://clients/{client_id}'.

Need to remove query params via regex similar as in init options.

**Comment by DavidFaizulaev** [comment]
my mistake, it's in docs.

**Comment by idanto** [comment]
```
Override - you can override the route and target attribute instead of taking them from the request object. In order to do that you should set a metrics object on your request with those attribute:
```
https://github.com/Zooz/prometheus-api-metrics#requestjs-http-request-duration-collector

We didn't implement regex in order not to do a complex operation in this package so we won't affect the performance of the application who use it. In addition because of the way you should use it (per request) you usually have a specific path you call it should cover most use cases.
